/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.BemTeVi;
import classes.Cachorro;
import classes.Gato;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public App() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPCategoria = new javax.swing.JPanel();
        jRBCachorro = new javax.swing.JRadioButton();
        jRBGato = new javax.swing.JRadioButton();
        jRBBemTeVi = new javax.swing.JRadioButton();
        jPDados = new javax.swing.JPanel();
        jLIdade = new javax.swing.JLabel();
        jLPeso = new javax.swing.JLabel();
        jLTamanho = new javax.swing.JLabel();
        jSIdade = new javax.swing.JSpinner();
        jTFPeso = new javax.swing.JTextField();
        jTFTamanho = new javax.swing.JTextField();
        jCBRaça = new javax.swing.JComboBox<>();
        jLKg = new javax.swing.JLabel();
        jLCm = new javax.swing.JLabel();
        jLRaça = new javax.swing.JLabel();
        jPResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAResultado = new javax.swing.JTextArea();
        jPBotoes = new javax.swing.JPanel();
        jBInformações = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));

        buttonGroup1.add(jRBCachorro);
        jRBCachorro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRBCachorro.setText("Cachorro");
        jRBCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCachorroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBGato);
        jRBGato.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRBGato.setText("Gato");
        jRBGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBGatoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBBemTeVi);
        jRBBemTeVi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRBBemTeVi.setText("Bem-te-vi");
        jRBBemTeVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBBemTeViActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCategoriaLayout = new javax.swing.GroupLayout(jPCategoria);
        jPCategoria.setLayout(jPCategoriaLayout);
        jPCategoriaLayout.setHorizontalGroup(
            jPCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCategoriaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRBBemTeVi)
                    .addComponent(jRBGato)
                    .addComponent(jRBCachorro))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPCategoriaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRBBemTeVi, jRBCachorro, jRBGato});

        jPCategoriaLayout.setVerticalGroup(
            jPCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCategoriaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jRBCachorro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBGato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBBemTeVi)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPCategoriaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRBBemTeVi, jRBCachorro, jRBGato});

        jPDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLIdade.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLIdade.setText("Idade");

        jLPeso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLPeso.setText("Peso");

        jLTamanho.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLTamanho.setText("Tamanho");

        jSIdade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jSIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaCampo(evt);
            }
        });

        jTFPeso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTFPeso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                App.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                App.this.focusLost(evt);
            }
        });
        jTFPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaCampo(evt);
            }
        });

        jTFTamanho.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTFTamanho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                App.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                App.this.focusLost(evt);
            }
        });
        jTFTamanho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaCampo(evt);
            }
        });

        jCBRaça.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCBRaça.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poodle", "Dog Alemão", "Spitz", "Bulldog" }));

        jLKg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLKg.setText("Kg");

        jLCm.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLCm.setText("Cm");

        jLRaça.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLRaça.setText("Raça");

        javax.swing.GroupLayout jPDadosLayout = new javax.swing.GroupLayout(jPDados);
        jPDados.setLayout(jPDadosLayout);
        jPDadosLayout.setHorizontalGroup(
            jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLTamanho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLIdade))
                    .addComponent(jLRaça))
                .addGap(28, 28, 28)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDadosLayout.createSequentialGroup()
                        .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFTamanho)
                            .addComponent(jTFPeso)
                            .addComponent(jSIdade, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLKg)
                            .addComponent(jLCm)))
                    .addComponent(jCBRaça, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPDadosLayout.setVerticalGroup(
            jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIdade)
                    .addComponent(jSIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLKg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCm))
                .addGap(18, 18, 18)
                .addGroup(jPDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBRaça, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLRaça))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jTAResultado.setColumns(20);
        jTAResultado.setRows(5);
        jScrollPane1.setViewportView(jTAResultado);

        javax.swing.GroupLayout jPResultadoLayout = new javax.swing.GroupLayout(jPResultado);
        jPResultado.setLayout(jPResultadoLayout);
        jPResultadoLayout.setHorizontalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPResultadoLayout.setVerticalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Botões"));

        jBInformações.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBInformações.setText("Informações");
        jBInformações.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInformaçõesActionPerformed(evt);
            }
        });

        jBLimpar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBSair.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBotoesLayout = new javax.swing.GroupLayout(jPBotoes);
        jPBotoes.setLayout(jPBotoesLayout);
        jPBotoesLayout.setHorizontalGroup(
            jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotoesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSair)
                    .addComponent(jBLimpar)
                    .addComponent(jBInformações))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPBotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBInformações, jBLimpar, jBSair});

        jPBotoesLayout.setVerticalGroup(
            jPBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotoesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jBInformações)
                .addGap(18, 18, 18)
                .addComponent(jBLimpar)
                .addGap(18, 18, 18)
                .addComponent(jBSair)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPBotoesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBInformações, jBLimpar, jBSair});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jPBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        limpar();
        jCBRaça.setVisible(false);
        jLRaça.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jBLimparActionPerformed

    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
        if (evt.getSource() instanceof javax.swing.JTextField) {
            javax.swing.JTextField campo = (javax.swing.JTextField) evt.getSource();
            campo.setBackground(new Color(184, 207, 229));
        }
    }//GEN-LAST:event_focusGained

    private void focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLost
        if (evt.getSource() instanceof javax.swing.JTextField) {
            javax.swing.JTextField campo = (javax.swing.JTextField) evt.getSource();
            campo.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_focusLost

    private void jBInformaçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInformaçõesActionPerformed

        if (jTFPeso.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo peso",
                    "Aviso", 0);
            jTFPeso.setText(null);
            jTFPeso.requestFocusInWindow();
            return;
        }

        if (jTFTamanho.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo tamanho",
                    "Aviso", 0);
            jTFTamanho.setText(null);
            jTFTamanho.requestFocusInWindow();
            return;
        }

        int idade = (Integer) (jSIdade.getValue());
        float peso = Float.parseFloat(jTFPeso.getText());
        float tamanho = Float.parseFloat(jTFTamanho.getText());

        if (jRBCachorro.isSelected()) {

            jCBRaça.setVisible(true);

            jLRaça.setVisible(true);

            if (jCBRaça.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(this, "Preencha o campo raça",
                        "Aviso", 0);
                jCBRaça.setSelectedIndex(-1);
                return;
            }

            String raça = "";

            if (jCBRaça.getSelectedIndex() != -1) {
                raça = jCBRaça.getSelectedItem().toString();
            }

            Cachorro objCachorro = new Cachorro(raça, idade, peso, tamanho);

            jTAResultado.setText(objCachorro.dados());

        } else if (jRBGato.isSelected()) {

            jCBRaça.setVisible(false);

            jLRaça.setVisible(false);

            Gato objGato = new Gato(idade, peso, tamanho);

            jTAResultado.setText(objGato.dados());

        } else if (jRBBemTeVi.isSelected()) {

            jCBRaça.setVisible(false);

            jLRaça.setVisible(false);

            BemTeVi objBemTeVi = new BemTeVi(idade, peso, tamanho);

            jTAResultado.setText(objBemTeVi.dados());

        } else {
            JOptionPane.showMessageDialog(this, "Preencha o campo categoria",
                    "Aviso", 0);
            return;
        }
    }//GEN-LAST:event_jBInformaçõesActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    private void validaCampo(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaCampo
        char tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != '.') {
            this.getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_validaCampo

    private void jRBCachorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCachorroActionPerformed

        jCBRaça.setVisible(true);

        jLRaça.setVisible(true);
    }//GEN-LAST:event_jRBCachorroActionPerformed

    private void jRBGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBGatoActionPerformed

        jCBRaça.setVisible(false);

        jLRaça.setVisible(false);
    }//GEN-LAST:event_jRBGatoActionPerformed

    private void jRBBemTeViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBBemTeViActionPerformed

        jCBRaça.setVisible(false);

        jLRaça.setVisible(false);
    }//GEN-LAST:event_jRBBemTeViActionPerformed

    private void limpar() {
        limpaCampos(jPCategoria);
        limpaCampos(jPDados);
        jTAResultado.setText(null);
        buttonGroup1.clearSelection();
    }

    private void limpaCampos(javax.swing.JPanel painel) {
        java.awt.Component[] componentes = painel.getComponents();
        for (int i = 0; i < componentes.length; i++) {
            if (componentes[i] instanceof javax.swing.JTextField) {
                javax.swing.JTextField campo = (javax.swing.JTextField) componentes[i];
                campo.setText(null);
            }

            if (componentes[i] instanceof javax.swing.JComboBox) {
                javax.swing.JComboBox combo = (javax.swing.JComboBox) componentes[i];
                combo.setSelectedIndex(-1);
            }

            if (componentes[i] instanceof javax.swing.JSpinner) {
                javax.swing.JSpinner campoSpinner = (javax.swing.JSpinner) componentes[i];
                campoSpinner.setValue(0);
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBInformações;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBSair;
    private javax.swing.JComboBox<String> jCBRaça;
    private javax.swing.JLabel jLCm;
    private javax.swing.JLabel jLIdade;
    private javax.swing.JLabel jLKg;
    private javax.swing.JLabel jLPeso;
    private javax.swing.JLabel jLRaça;
    private javax.swing.JLabel jLTamanho;
    private javax.swing.JPanel jPBotoes;
    private javax.swing.JPanel jPCategoria;
    private javax.swing.JPanel jPDados;
    private javax.swing.JPanel jPResultado;
    private javax.swing.JRadioButton jRBBemTeVi;
    private javax.swing.JRadioButton jRBCachorro;
    private javax.swing.JRadioButton jRBGato;
    private javax.swing.JSpinner jSIdade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAResultado;
    private javax.swing.JTextField jTFPeso;
    private javax.swing.JTextField jTFTamanho;
    // End of variables declaration//GEN-END:variables
}
